name: dirtbag backend

on:
  push:
    paths:
      - "backend/**/*"
      - ".github/workflows/backend.yml"
    branches: [ "main" ]
  pull_request:
    paths:
      - "backend/**/*"
      - ".github/workflows/backend.yml"
    branches: [ "main" ]

permissions:
  contents: read


env:
  DB_FILE: /tmp/problems.json
  SENTRY_RELEASE_AUTH_TOKEN: ${{ secrets.SENTRY_RELEASE_AUTH_TOKEN }}
  SENTRY_ORG: gnerd
  SENTRY_PROJECT: dirtbag-backend
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DB_FILE_TRIPS: "/tmp/trips.json"
  DB_FILE_27CACHE: "/tmp/27.json"
  DB_FILE_TODODS: "/tmp/todos.json"
  DB_FILE_SENDS: "/tmp/sends.json"
  WEATHER_DIRECTORY: "/tmp/"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest anyio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: "Deploy on fly.io"
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only